### ISSUE TITLE
How to use nobrainer realtime with Rails 5 Action Cable?

### ISSUE THREAD

**Issue by chardy** [NoBrainerORM/nobrainer#217]
Anyone can help?

Thanks.

**Comment by jeroenvisser101** [comment]
There's a WIP #192, but this isn't possible right now AFAIK

**Comment by chardy** [comment]
Hey guys,

Please see this post:

https://blog.phusion.nl/2016/08/04/using-rails-5-actioncable-and-rethinkdb-to-build-a-reactive-websocket-app/

**Comment by zedtux** [comment]
That blog article is really nice and thank you @chardy for sharing it!

What shall we do with this issue? Shall we add shorter version to the "RECIPES" section of nobrainer.io, or anything?

**Comment by zedtux** [comment]
A little bit more than a year later, no answer to my comment, I'm closing it.
