### ISSUE TITLE
Fixtures? 

### ISSUE THREAD

**Issue by tacoplz** [NoBrainerORM/nobrainer#236]
Is it possible to use fixtures with the NoBrainer ORM when testing? I have not been successful trying to get this to work. On Github- rethinkdb/rails-nobrainer-blog has the file './test/test_helper.rb'

```
ENV["RAILS_ENV"] = "test"
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'

class ActiveSupport::TestCase
  # Setup all fixtures in test/fixtures/*.(yml|csv) for all tests in alphabetical order.
  #
  # Note: You'll currently still have to declare fixtures explicitly in integration tests
  # -- they do not yet inherit this setting
  fixtures :all

  # Add more helper methods to be used by all tests here...
end
```

How do I declare fixtures explicitly? (I've pasted the below line from above)
`Note: You'll currently still have to declare fixtures explicitly in integration tests`

**Comment by nviennot** [comment]
You should be able to use fixtures. I've never used them, so I don't know how they work.
I've always used Factory Girl, and works great with it.

**Comment by tacoplz** [comment]
Sorry for the delayed response-
When I run tests with Ruby, Rails, & NoBrainer out of the box: 
`localhost-2:react Stephan$ rake test`
`rake aborted!
NoMethodError: undefined method `fixtures' for ActiveSupport::TestCase:Class
/Users/Stephan/ruby/react/test/test_helper.rb:7:in `<class:TestCase>'
/Users/Stephan/ruby/react/test/test_helper.rb:5:in `<top (required)>'
/Users/Stephan/ruby/react/test/models/blog_image_test.rb:1:in `require'
/Users/Stephan/ruby/react/test/models/blog_image_test.rb:1:in `<top (required)>'
/Users/Stephan/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:11:in `require'
/Users/Stephan/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:11:in `block in require_files'
/Users/Stephan/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:10:in `each'
/Users/Stephan/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/test_unit/test_requirer.rb:10:in `require_files'
/Users/Stephan/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/test_unit/minitest_plugin.rb:62:in `rake_run'
/Users/Stephan/.rvm/gems/ruby-2.4.0/gems/railties-5.0.2/lib/rails/test_unit/testing.rake:15:in `block in <top (required)>'
/Users/Stephan/.rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => test
(See full trace by running task with --trace)`

It appear having the line:
`fixtures :all`
in test_helper.rb causes some sort of problem that I do not have the ability to correct. Currently I have just commented line 7 (shown above) of test_helper.rb out. 
I run my tests by defining the db rows in each test or in a hook at the beginning of the unit test file. 

Any thoughts?

**Comment by nviennot** [comment]
I've never used fixtures, so I'm afraid I'm useless here

**Comment by zedtux** [comment]
For the record, one could check [this SO](https://stackoverflow.com/questions/8640802/undefined-method-fixtures-for-activesupporttestcaseclass-while-testing-wi) in order to see if fixtures are working with nobrainer.
