### ISSUE TITLE
DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1.

### ISSUE THREAD

**Issue by zedtux** [NoBrainerORM/nobrainer#257]
It seems that warning comes from nobrainer with the latest Rails version (6.0.2.1):

```
DEPRECATION WARNING: `Module#parent` has been renamed to `module_parent`. `parent` is deprecated and will be removed in Rails 6.1. (called from <class:ChefNode> at /application/app/models/chef_node.rb:51)
```

At that line I have a `belongs_to :cluster`.

**Comment by nviennot** [comment]
I see. Can you make a pull request to fix all of this?

**Comment by zedtux** [comment]
This should have been fixed from [that line](https://github.com/NoBrainerORM/nobrainer/blob/master/lib/no_brainer/document/association/core.rb#L54).

I'm closing for now.
