### ISSUE TITLE
Dear Contributors, we'd like to discuss purchasing the domain name "nobrainer.io"

### ISSUE THREAD

**Issue by christopherreay** [NoBrainerORM/nobrainer#283]
We are building a trading platform based around the idea of community trading. We have currently about 60 members, many of whom are coders.

We'd super like to buy your domain name. We could put a link to your project on our page (with gratitude to...), and since we are charging membership, perhaps we could funnel some of that to your project on a monthly basis? Umm at the moment we are looking at a few hundred dollars a month, but we dont know what they future will hold. We arent trying to make a massive membership base, ... well thats not the plan at the moment. Or we could just pay you for the domain name in a one off. Or whatever you ilke.

warm regards :) christopher

**Comment by nviennot** [comment]
Hi Christopher, not at this point. Perhaps we can put a link to your page instead?

**Comment by christopherreay** [comment]
that's super generous.

we're going live... well going beta, end of February with the trading platform.

if you have any interest in trading (we invest in good ethical projects), i think i can swing some free accounts.

best of luck and thank you again.

I'll close the issue and reopen when we are live

**Comment by christopherreay** [comment]
is there a number? (best suits voice lol)

**Comment by nviennot** [comment]
Not at this point. We can have this conversation once you have a viable product.

**Comment by christopherreay** [comment]
i thought that was what you meant.

thank you for the deep coherence xx
