### ISSUE TITLE
Polymorphic Associations 

### ISSUE THREAD

**Issue by jakcharlton** [NoBrainerORM/nobrainer#51]
Any way to do this in Nobrainer?  

According to the documentation, the 'has_many' and 'belongs_to' don't support the normal Rails attributes to enable this

**Comment by radicaled** [comment]
Did this ever land? I don't see it in the roadmap anymore and NoBrainer doesn't recognize the `polymorphic` symbol on a `belongs_to` -- but NoBrainer does and names stuff slightly differently, so I'm not entirely sure I'm using the right symbol.

**Comment by nviennot** [comment]
I'm not sure why I removed it after: https://github.com/nviennot/nobrainer.io/commit/490b635bb66c6a6fe39d5293fad9e8b34918c593

Do you have a usecase where using a polymorphic belongs_to is better compared to one? If I'm convinced that they are useful, it would motivate me to get it done.

Thank you :)

**Comment by radicaled** [comment]
> Do you have a usecase where using a polymorphic belongs_to is better compared to one? If I'm convinced that they are useful, it would motivate me to get it done.

I'm not sure my use-case is any more special than the typical ActiveRecord case. I'm using composition over inheritance, so I've got data models that represent user generated content, and these various data models all implement certain patterns so that they can be combinations of the following: reportable, voteable, taggable, displayable, moderatable, that sort of thing. Most items are reportable, but not all items are voteable, etc etc.

I was planning on using polymorphism to avoid having to know about the internals and types of each data model for the most part. Single code path, less errors, that stuff.

**Comment by nviennot** [comment]
I think there have been some confusion.

1) This is currently supported: a belongs_to that points to a model that have a bunch of subclasses
2) This is not supported: a belongs_to that could point to any model

I think your example is doing 1), right?

If not, feel free to show some code, so we can establish a common ground.

**Comment by radicaled** [comment]
Ah, these aren't subclasses, I'm using modules to mix in behavior for certain classes.

I have code like this:

```ruby
module Moderatable
   extends ActiveRecord::Concern
   included do
      field :removed_at, type: Time
      field :removed_reason, type: String
   end

   def remove!
     # ...
   end
end

# ... several other behaviors for various things

class Comment
   include NoBrainer::Document
   include Moderatable
   include Voteable
   include Reportable 
end

class AbuseReport
   include NoBrainer::Document

  field :reported_at, type: Time
  belongs_to :reporter, class_name: 'User'
  belongs_to :handler, class_name: 'AdminUser'
   # this is where I'd do a belongs_to :reportable, polymorphic: true to point at a Comment / Image / etc.
   # ...
end

class Vote
  field :score, type: Integer
  belongs_to :voter, class_name: 'User'
  # See above
  # ...
end
```

I avoided taking a subclassing based approach because my hierachy wouldn't make any sense, I think:

Post > Reportable > Voteable > ... ?!

Well, it may be possible to make that work but it seems rather... off.

**Comment by nviennot** [comment]
That's a compelling example. I'll see about implementing this feature :)

However, this is quite substantial to implement, and I don't have much time these days, so I can only give you a promise that I'll implement it at this time. I'll try to get it done by the end of the month.

**Comment by radicaled** [comment]
:+1: 

Thanks. I'll manage a work around somehow until this feature lands.

**Comment by dvergeylen** [comment]
Hi @nviennot,

Thank you for the work already done on this ORM.

I currently have another example under the hood. I use to give some Rights to Users and Groups (of users). This allows me to give general rights to group(s) and fine-tune some permissions for some users only (for admin purposes like unlock, edit posts, ...).

This way we have `belongs_to :editor, :polymorphic => :true` in my Right model. This illustrates your case '2)', doesn't it?

**Comment by nviennot** [comment]
Sure, or you could use regular polymorphism:

```ruby
class Right
  field :permissions, type: Array
end

class UserRight < Right
  belongs_to :user
end

class GroupRight < Right
  belongs_to :group
end
```

**Comment by dvergeylen** [comment]
will give this a try :simple_smile:

**Comment by nviennot** [comment]
IMHO, simpler would be to store a `field :permissions, type: Array` in `User` and `Group` which would store a list of things someone can do. So no `Right` model. Maybe that logic (including the field declaration) could be encapsulated in a `HasRights` module or something.

```ruby
module HasRights
  included do
    field :permissions, type: Array
  end
  
  def can_perform?(something)
    permissions.include?(stomething)
  end
end

class User
  include HasRights
end

class Group
  include HasRights
end
```
